[project]
name = "controlflow-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "controlflow>=0.12.1",
 "jupyter>=1.1.1",
 "python-dotenv>=1.0.1",
]
